defmodule Tilde.Demo.Password do
  @moduledoc "Central password policy for the standalone web + SSH demo."

  @env_var "TILDE_DEMO_PASSWORD"
  @app_key :demo_password
  @bytes 24

  @doc "Environment variable used to configure the demo password."
  @spec env_var() :: String.t()
  def env_var, do: @env_var

  @doc "Returns the configured password, or generates and stores one once."
  @spec get() :: String.t()
  def get do
    case Application.get_env(:tilde, @app_key) do
      password when is_binary(password) and password != "" -> password
      _other -> configure()
    end
  end

  @doc "Configures the demo password from opts/env or a generated value."
  @spec configure(keyword()) :: String.t()
  def configure(opts \\ []) do
    password = resolve(opts)
    Application.put_env(:tilde, @app_key, password)
    password
  end

  @doc "Resolves the password from explicit opts, env, or generated fallback."
  @spec resolve(keyword()) :: String.t()
  def resolve(opts \\ []) do
    opts
    |> Keyword.get(:password)
    |> present_or(System.get_env(@env_var))
    |> present_or(generate())
  end

  @doc "Constant-time comparison against the configured demo password."
  @spec valid?(String.t()) :: boolean()
  def valid?(supplied) when is_binary(supplied), do: Plug.Crypto.secure_compare(supplied, get())
  def valid?(_supplied), do: false

  @doc "Returns an Erlang SSH password callback for the configured password."
  @spec ssh_password_fun(String.t()) :: (charlist(), charlist() -> boolean())
  def ssh_password_fun(password \\ get()) do
    password_chars = String.to_charlist(password)
    fn _user, supplied_password -> supplied_password == password_chars end
  end

  @doc "Generates a URL-safe random password."
  @spec generate() :: String.t()
  def generate do
    @bytes
    |> :crypto.strong_rand_bytes()
    |> Base.url_encode64(padding: false)
  end

  @doc "Human-facing description of password configuration."
  @spec help() :: String.t()
  def help, do: "generated by default; override with --password or #{@env_var}"

  defp present_or(value, _fallback) when is_binary(value) and value != "", do: value
  defp present_or(_value, fallback), do: fallback
end
