defmodule Tilde.Transport.SSH.Demo do
  @moduledoc """
  SSH server for the Tilde TUI demo.

  Start it from `iex -S mix`:

      {:ok, _pid} = Tilde.Transport.SSH.Demo.start_link(port: 4022)

  Then connect with OpenSSH:

      ssh tilde@localhost -p 4022 \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null

  Password: generated by default. Pass `:password` or set `TILDE_DEMO_PASSWORD` to choose one.
  """

  use GenServer

  alias Tilde.Session.Server, as: SessionServer
  alias Tilde.Transport.SSH.Keys

  @default_port 4022

  @type option ::
          {:port, :inet.port_number()}
          | {:system_dir, Path.t()}
          | {:password, String.t()}
          | {:session_server, SessionServer.name() | nil}
          | {:session_mode, :private | :shared}

  @doc "Starts the demo SSH daemon under a GenServer."
  @spec start_link([option()]) :: GenServer.on_start()
  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts)
  end

  @doc "Returns the daemon reference."
  @spec daemon_ref(GenServer.server()) :: term()
  def daemon_ref(server), do: GenServer.call(server, :daemon_ref)

  @impl true
  def init(opts) do
    port = Keyword.get(opts, :port, @default_port)
    password = Tilde.Demo.Password.configure(opts)
    system_dir = Keyword.get_lazy(opts, :system_dir, &default_system_dir/0)
    session_server = Keyword.get(opts, :session_server)
    session_mode = Keyword.get(opts, :session_mode, :private)

    with {:ok, _registry_pid} <- Tilde.Session.Registry.ensure_started(),
         {:ok, _server_pid} <- ensure_session_server(session_server),
         {:ok, _apps} <- :application.ensure_all_started(:ssh),
         {:ok, system_dir} <- Keys.ensure_system_dir(system_dir),
         {:ok, daemon_ref} <-
           start_daemon(port, system_dir, password, session_server, session_mode) do
      {:ok, %{daemon_ref: daemon_ref, port: port, system_dir: system_dir}}
    else
      {:error, reason} -> {:stop, reason}
    end
  end

  @impl true
  def handle_call(:daemon_ref, _from, state), do: {:reply, state.daemon_ref, state}

  @impl true
  def terminate(_reason, %{daemon_ref: daemon_ref}) do
    :ssh.stop_daemon(daemon_ref)
  end

  def terminate(_reason, _state), do: :ok

  defp ensure_session_server(nil), do: {:ok, self()}

  defp ensure_session_server(server) do
    SessionServer.ensure_started(server, session: Tilde.Demo.Live.demo_session())
  end

  defp start_daemon(port, system_dir, password, session_server, session_mode) do
    :ssh.daemon(port, [
      {:system_dir, String.to_charlist(system_dir)},
      {:auth_methods, ~c"password"},
      {:pwdfun, Tilde.Demo.Password.ssh_password_fun(password)},
      {:ssh_cli,
       {Tilde.Transport.SSH.Channel,
        [[width: 100, session_server: session_server, session_mode: session_mode]]}},
      {:parallel_login, true}
    ])
  end

  defp default_system_dir do
    Path.expand("_build/tilde_ssh/system")
  end
end
